name: MyST GitHub Pages Deploy

on:
  workflow_run:
    workflows: ["Build and execute","monthly-build"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    uses: eds-book/notebooks-workflows/.github/workflows/deploy.yaml@main